### ISSUE TITLE
Throttle warning does not work on custom model

### ISSUE THREAD

**Issue by Drashiel** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#134]
Hi,
I have a custom model on my Horus running 1.3.01. When I boot up radio with throttle stick at not minimal and this custom model selected, I don´t have throttle warning. Nor can add on warning setup page.

I think it could be great have this feature since it could be disabled on warning setup.

**Comment by Adelaxie** [comment]
1. Throttle channel can be assigned in custom mode.
2. Throttle channel name can be modified under custom mode.
3. Throttle warning is based on the value of the phisical stick position.

So, very complex if the warning added.

**Comment by Drashiel** [comment]
You can add a channel selection on switch warning setup to select what channel throttle is and add position read as rest of models.

**Comment by Adelaxie** [comment]
yes, if want to add , then need customers to set it manually/.

**Comment by Drashiel** [comment]
So, it is possible. Maybe you can consider add on next firmware release?

**Comment by Adelaxie** [comment]
Will suggest and if any progress will post it here. Thanks for sugegstion.

**Comment by Adelaxie** [comment]
supported in next release v1.2.01 (v1.5.01 for x12s)
