### ISSUE TITLE
SXR config page:It is not possible to select any option

### ISSUE THREAD

**Issue by Adelaxie** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#147]
![image](https://user-images.githubusercontent.com/6251929/33000871-949e8c80-cde5-11e7-813a-ef92ffb66f89.png)

**Comment by Crunch69** [comment]
this occurs if a RX is not bound

**Comment by Adelaxie** [comment]
@Crunch69  If RX not bound, all options will be hide.
