### ISSUE TITLE
Date setup not functioning after 1.4.04

### ISSUE THREAD

**Issue by alex998r** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#152]
Hello, after I have upgraded to 1.4.04 , I can't set the date from the SYS/TIME option menu.
When I select the first line to setup date, a brown square appears on the right side, probably it should be the calendar, but it fails, some pictures will be better than a lot of words.
Thanks for your help
ALessandro
![20171201_203150](https://user-images.githubusercontent.com/29479191/33500826-994b6bce-d6da-11e7-9c28-0565b2f5f0b8.jpg)
![20171201_203135](https://user-images.githubusercontent.com/29479191/33500829-996b147e-d6da-11e7-8ecb-2f2a0fd92b89.jpg)
![20171201_203120](https://user-images.githubusercontent.com/29479191/33500830-998a1f40-d6da-11e7-962e-3982b8cbb8cd.jpg)

**Comment by Adelaxie** [comment]
#146 
Same
Please pay attention on the latest firmware to test when release/
Thanks for report Alex/
