### ISSUE TITLE
SExL and SExR  opposite position in main page only on X12S

### ISSUE THREAD

**Issue by Adelaxie** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#155]
If you now press PgDn, then you will see "SExL" and SExR "in the display.If you now press the button on the left, then we will see in the display that it is the right button.

**Comment by janekx** [comment]
Not in X10 and lattest 1.2.01FW

**Comment by kilrah** [comment]
"Adelaxie added this to the v1.2.02 (1.5.02 for x12s) milestone"

**Comment by Adelaxie** [comment]
@janekx  Yes， it is fixed and v1.2.01 is only tested closed so I edited the milestone name as v1.2.02.
