### ISSUE TITLE
[enhancement] More PITCH curve points in Helicopter Model

### ISSUE THREAD

**Issue by jperez-murcia** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#160]
For finest and better helicopter PITCH curves setup, much more than 7 points are needed. For F3C (helicopter acrobatics) setups, as more points, a better and smooth setup will be performed. Seven points aren't enough.

OpenTX curve handling would be great in FrOS. A lot of curve points and full freedom to configure such points,

Please, consider this enhancement for future releases because; seven point are enough for sport flying, but not for competition.

Great work ...

**Comment by Adelaxie** [comment]
@jperez-murcia  Now the point can support up to 22. what version do you use?

**Comment by jperez-murcia** [comment]
Hi Adela...

AFAIK I'm using, last version? ,... 1.4.04 .... but I can't configure over 7 points ... may be I'm missing something?

regards

**Comment by Adelaxie** [comment]
Please select MULTI_LINE or MULTI_SMOOTH mode of the dropdown widget in the upper middle of the page.

**Comment by MIKE-DAILEY** [comment]
@Adelaxie I think the MULTI_LINE or MULTI_SMOOTH function might be broken.  You can set 21 points but the points will not scroll to reach past P7.

**Comment by Adelaxie** [comment]
@jperez-murcia  any problems still? If No more question please close the issue.

**Comment by jperez-murcia** [comment]
my apologies .... no additional problems.

**Comment by Adelaxie** [comment]
Thx
