### ISSUE TITLE
Typo in RATES/EXPO screen:  'FIGHT MODE' instead of 'FLIGHT MODE'

### ISSUE THREAD

**Issue by swirlymaple** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#164]
Affects all versions of FrOS up to 1.2.02.

In the RATES/EXPO screen, there is a selector in the top-left that can be set to 'SWITCH' or 'FLIGHT MODE'. However, when it is toggled to 'FLIGHT MODE', it is misspelled as 'FIGHT MODE'.

![fight mode](https://user-images.githubusercontent.com/35134519/34603989-07bfe3c8-f1bb-11e7-9568-e594a6959513.jpg)

**Comment by Adelaxie** [comment]
:(  fixing it now.
