### ISSUE TITLE
Name change of a mixer in CUSTOM model does not work.

### ISSUE THREAD

**Issue by liukku56** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#171]
How do I change the name for a mixer, eg. Mixer5 to be Flap LEFT when I setup a Custom model in FrOS? I have tried many times but when I have changed the name and leave the menu, it changes back to eg Mixer5.
I am using Hardware X10 EU14 and FW 1.2.02

/Ville

![02-01-14-16-04custom tes](https://user-images.githubusercontent.com/35923239/35512614-ac0cc826-0500-11e8-994d-6778a4761a50.jpg)

**Comment by Adelaxie** [comment]
@liukku56  Hi,Please long ENT to save and RTN to quit without save.

**Comment by MIKE-DAILEY** [comment]
I missed that one!  Tested and working.

**Comment by liukku56** [comment]
Thank you Adelaxie! Testing and it is working perfect! 
/Ville

**Comment by Adelaxie** [comment]
@liukku56  If it is resolved please close the issue .
reopen ?
