### ISSUE TITLE
electric brake

### ISSUE THREAD

**Issue by robertobuti** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#175]
Hello,
i have a suggestion to improve the system, provide some functions to manage electric brake, normally we use a slider to brake the plane  on dedicated channel, with proportional intensity. I like set an alarm if you forget the brake inserted for long time. (can't be ON too much, dangerous for temperature brake and battery), more a track player on slider treshold will be useful to advise you have brake inserted.

thank

**Comment by Woita2095** [comment]
Well,
but this is only one separate thing.
Maybe would be better to have a timer, which could be started by a switch (of course, logical switch too). And then use the value of this timer  in functions, especially in the "Special functions"). This way would be able to playback track with warnings etc.

**Comment by MIKE-DAILEY** [comment]
With the current X10S/X10 firmware that can be done with the delay function in the logic switches and in the next release for the X12S.

**Comment by Woita2095** [comment]
So, this suggestion #175 looks to be solved then :-)

**Comment by MIKE-DAILEY** [comment]
I would think so.  Just program a logic switch to monitor the brake channel with delay.  The logic switch becomes true with the brake on and the delay time true.  Add the logic switch to the special functions that plays a brake warring wav file.  Available now with the X10S.X10 and soon with the X12S,

**Comment by Woita2095** [comment]
There is FW 1.5.03L for X12S, where it is done allready.

**Comment by MIKE-DAILEY** [comment]
Yes, but that is beta and not released to the FrSky website yet.  Should be soon though.

**Comment by Woita2095** [comment]
The logical switches seems to be very strong tool.
Certainly would be great if there was more LS's. 
8 of Logical Switches is too little. 32 would be better, 64 would be great!!!

**Comment by Woita2095** [comment]
Agree. I just wanted to write:

"Maybe it worths to create a new issue, to increase number of the Logical switches?"

So I am going to write it as a new idea.

**Comment by Adelaxie** [comment]
if anything else not resolved please reopen the issue. @robertobuti
