### ISSUE TITLE
Possibility to copy flight modes in FrOS software 1.2.03 and 1.2.03.

### ISSUE THREAD

**Issue by liukku56** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#183]
I want to be able to copy flight modes so I do not have to redo all settings again for every flight mode.

Hardware: X10 EU14
SoftWare: 1.2.03
PhysID: 23

**Comment by janekx** [comment]
You mean copy FM from model to model? Why not copy model and change other items.

**Comment by liukku56** [comment]
Hello janekx!
No, I mean to be able to copy flight modes for the present model.
---

**Comment by andymeade** [comment]
Similar to my #96 - every flight mode needs expo rates etc setting up very carefully.  Ideally needs a copy function!

**Comment by liukku56** [comment]
Thank you andymeade, I mean exactly as you point out.
---

**Comment by janekx** [comment]
duplicate to #96

**Comment by stanley1211** [comment]
This is urgent needed. I found it very tedious to program without this copy function, and it's easy to make misstake during programming
