### ISSUE TITLE
RPM sensor not working fine D8 telemetry

### ISSUE THREAD

**Issue by Drashiel** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#202]
Hi 
I have a Horus updated 1.5.03L version and have a issue with telemetry.
With a D8 module, RPM sensor mark frequency instead of RPM. In fact, change blades number does not make any change at output.
Same setup with a DHT module works fine.
Regards.

**Comment by strgaltdel** [comment]
Ich kehre zurück am 11.06.2018.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[FrSky-OS/HORUS-X10-X10S-X12S-bug-report] RMP sensor not working fine (#202)" gesendet am
24.05.2018 18:08:32.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by Drashiel** [comment]
Issue still persist on FW 1.6.01, RPM display frequency x2 instead of RPM.

**Comment by Adelaxie** [comment]
Confirmed that its fixed on latest firmware by mail. 
Thanks.
