### ISSUE TITLE
Horus 10s hung and I had to turn it off and on again

### ISSUE THREAD

**Issue by Derry061** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#215]
I was playing with my brand new 10s and using the 'SXR Setup' on the SYS menu. I had a S*R rx bound to the tx. I was switching back and forth to screen 2, trying to figure out the settings (I cant find any documentation giving details). Suddenly everything froze. None of the controls would respond. I had to turn off the Tx and turn it on again to get it to work. I am using version 1.2.05 which seems to be the latest full release.

**Comment by Adelaxie** [comment]
Please help to confirm that we have fixed it on latest release. you can download the firmware from DOWNLOAD section of FrSKY website.
thanks in advance.

**Comment by Derry061** [comment]
I have installed Frsky OS v 1.3.03 Beta and tried to reproduce the problem without success. so I guess that it is fixed.
Derry061

**Comment by Adelaxie** [comment]
Thanks for your report.
