### ISSUE TITLE
Horus X12S firmware 1.6.01 flex won't bind 2.4Ghz

### ISSUE THREAD

**Issue by alex998r** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#220]
Hello, I upgraded my X12S to the latest firmware 1.6.01, flex version (X12S_FLEX_1601_Beta0823_frtx.bin), after that it won't bind anymore with the internal RF module at 2.4Ghz. The external module at 868Mhz instead is ok. I then loaded the EU version and all returned to function properly, obviously I've lost the FLEX on the 868Mhz.
Regards

**Comment by Adelaxie** [comment]
>after that it won't bind anymore with the internal RF module at 2.4Ghz
Flex firmware is only for 900Mhz products.

**Comment by alex998r** [comment]
Ok, thanks, since it si not clearly explained I tryied it

**Comment by Adelaxie** [comment]
okay and If no more prob I will close the issue.
