### ISSUE TITLE
Firmware V1.6.01 EU Beta Dual/Rate mistake

### ISSUE THREAD

**Issue by isidresa** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#222]
Please see the following pdf document:
[frsky info dual_rate problem in firmware 1.6.01 beta.pdf](https://github.com/FrSky-OS/HORUS-X10-X10S-X12S-bug-report/files/2577550/frsky.info.dual_rate.problem.in.firmware.1.6.01.beta.pdf)

**Comment by choochoo2** [comment]
I just discovered the same problem in X10s firmware 1.3.01 beta trying to adjust flap positions.  Exploring a bit further, this problem applies to all variants, line, multi-line, smooth, etc. including expo, where it will not accept negative numbers for any of the parameters.  This whole menu section seems to be buggy.

**Comment by Adelaxie** [comment]
We will release normal version of v1.6.1 for x12s / v1.3.1 for x10/s which fix some bugs like this in v1.6.1beta / 1.3.1beta. Thanks for your reports.

**Comment by choochoo2** [comment]
This problem has been corrected in X10 1.3.01 release version.  Negative values are now working as expected.

**Comment by Adelaxie** [comment]
@choochoo2  Thanks for the confirmation.
