### ISSUE TITLE
FrSky Smart Port Lipo Sensor FLVSS on my Horus x12s displaying wrong individual cell voltages

### ISSUE THREAD

**Issue by ninodesposati** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#227]
I have a FrSky Smart Port Lipo Sensor FLVSS on my Horus x12s Ver 1.6.01. When I select to the individual cells page to show voltage it shows the current individual voltage and number of the cell then it quickly changes to the total voltage on cells  1-6 even though it's hooked up to a 4 cell battery. Any ideas. I have attached a video to show. Thanks

https://youtu.be/Q0TMLSVkFMI

**Comment by Adelaxie** [comment]
@ninodesposati Please test the latest 1.6.03beta firmware on FrSky website, it should have been fixed.
