### ISSUE TITLE
1.6.01 Log files records of-of-bound values on my X12S, with R9M module

### ISSUE THREAD

**Issue by OlivierC-FR** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#228]
FROS 1.6.01 Flex
R9M Flex 1228

See the out of bound values recorded, not sure if that's from the X12S itself, or from the R9M module.
It's unlkely it's from the iNav telemetry, because the A4 column is also later wrong, aswell the RX battery, and these two are not from the flight control.

Not a SDcard issue, it's plenty fast enough, and tested under load.

![x12s1601_log](https://user-images.githubusercontent.com/25566932/51102700-4472d400-17e0-11e9-9aaf-877138248008.jpg)

**Comment by Adelaxie** [comment]
@OlivierC-FR Please test the latest firmware of R9(190201). it should have been fixed.
