### ISSUE TITLE
Throttle timer X12S. 

### ISSUE THREAD

**Issue by Drashiel** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#229]
Hi
Could you consider change timer based on %th to gimbal position?
On IC engines, when servo is reversed there is no way to use time based on throttle because gimbal to maximum stops timer and move to minimal causes timer forwards.

**Comment by Adelaxie** [comment]
Will do it.thanks

**Comment by Adelaxie** [comment]
Confirmed by other users that its fixed on v1.6.03 beta , please check @Drashiel
