### ISSUE TITLE
Horus x12s - FROS  1.6.04 LBT - Slow flight mode problem...

### ISSUE THREAD

**Issue by Lombardoa** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#248]
As above, when i put some value on Slow variable and try, i no have no one result on servo.  Same  problem on heli program, Plane program and so on. Before update it worked fine. Please. can you check... thanks in advance...A. Lombardo

![Issue-1](https://user-images.githubusercontent.com/50540767/59567974-62d14a00-9074-11e9-9b1b-243abf60c361.jpg)

![Fw-1](https://user-images.githubusercontent.com/50540767/59567976-767cb080-9074-11e9-933a-ae87a694da2f.jpg)

**Comment by FrSky-GX** [comment]
we haven't reproduced this problem , could you make a vedio with details?

**Comment by Lombardoa** [comment]
I can make a video... but i can't put it here...only pictures...

**Comment by Lombardoa** [comment]
As I have already written, with  a airplane program, whatever value I put, the speed of the servos does not change. I don't see any delay. While the voice or sound that I associated with the interested key, SWB_DN, with the play track function, results with a delay, the audio is bad for the whole time relative to the value inserted on SLOW. After this delay the audio works well.
Hope you can reproduce...

**Comment by Lombardoa** [comment]
[FrSky X12S Horus User Guide 20180928 - page 46.pdf](https://github.com/FrSky-OS/HORUS-X10-X10S-X12S-bug-report/files/3324346/FrSky.X12S.Horus.User.Guide.20180928.-.page.46.pdf)

Adela, please ... on page 46 of the manual it is written that if the value written in SLOW MODE is used to avoid fast drives, such as flaps, gears, ailerons. As I have already explained to you, in my case, with the AIRPLANE program, it does not work. If I want, a delay, for example on FLAPS, I have to use the SPEED function, described on page 30.
While, it should also work in SLOW MODE ... Why doesn't it happen? ... Am I doing something wrong? Thanks for the support...
