### ISSUE TITLE
Flightmode problem DR/Expo from Flightmode 6

### ISSUE THREAD

**Issue by MGausGS** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#249]
Hardware: HORUS X12S
Fimrware: 1.6.04L

DR/Expo problem from flight mode 6.

I can enter Expo values, Weight or Offset but nothing happens in the graphic to the right.
Normally the graphic should change accordingly, as it does with flight modes Launch to Landing. 

It is also not possible to select a 7 or 21 point curve.
The set values are also not saved.

**Comment by choochoo2** [comment]
With Glider type, none of the RATE/EXPO settings seem to work for flight modes 6-9.

**Comment by MGausGS** [comment]
I re-tested it.
It works neither with an existing model nor with a newly created model.

**Comment by WismyYao** [comment]
Thanks for your bug report.  I will fix it .

**Comment by WismyYao** [comment]
fixed
