### ISSUE TITLE
FLAP SET Bugs

### ISSUE THREAD

**Issue by choochoo2** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#251]
The FLAP SET menu has multiple bugs.

When the menu is first entered it appears like this where a switch can be assigned to settings # 1.
![FLAP SET 1](https://user-images.githubusercontent.com/36141206/62333509-9c211600-b478-11e9-82af-a7fb1ea789ee.jpg)
If you change to the # 2 screen and back to screen # 1, it now appears like this, where the switch assignment is greyed out.
![FLAP SET 2](https://user-images.githubusercontent.com/36141206/62333702-5fa1ea00-b479-11e9-9462-db43dd0b64bf.jpg)

Worse, it appears the # 1 offset value of 50 used in the examples applies always, regardless of the switch position and the # 2 settings.  In other words, the menu is unusable.

The fact that these bugs are just now being reported suggests this menu isn't being used.  This would make sense given that its current design isn't very useful.  Please see issue #250 for suggestions on how to make this menu more useful.

**Comment by WismyYao** [comment]
Thanks for your bug report .

**Comment by WismyYao** [comment]
fixed
