### ISSUE TITLE
Logic Switch "NOT" operation displays extraneous data

### ISSUE THREAD

**Issue by choochoo2** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#252]
This isn't a particularly important bug but you might want to know about it anyway.

Unlike the other LOGIC SWITCH operations, the NOT operation uses only one source and the data in the second source is meaningless.  Here is an example logic switch using NOT.  The data in the second source fields are greyed out.

![07-31-15-00-33Zazzy     _LI](https://user-images.githubusercontent.com/36141206/62334280-e952b700-b47b-11e9-93ba-74d783e820d8.jpg)

Although the greyed out data is meaningless, it still displays on the Logic Switch summary screen...

![07-31-15-01-11Zazzy     _LI](https://user-images.githubusercontent.com/36141206/62334318-1737fb80-b47c-11e9-88e3-33c4d968d0a1.jpg)
… and it displays on the Logic Switch status screen:

![07-31-15-02-25Zazzy     _LI](https://user-images.githubusercontent.com/36141206/62334375-4a7a8a80-b47c-11e9-8903-fee3ea041c7b.jpg)

The circled data fields should be blank on these last two screens.

**Comment by WismyYao** [comment]
Thanks for your bug report.

**Comment by WismyYao** [comment]
Fixed in X12S 1.6.06 / X10(s) 1.3.06
