### ISSUE TITLE
Bug in editing Flight Mode names

### ISSUE THREAD

**Issue by choochoo2** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#253]
Another not very important bug you might want to fix when you get a chance; The process for editing Flight Mode names differs from editing Model names in the System menu.  The procedure should be the same.

Specifically, editing Model names, after the name appears as desired the user can terminate the edit and save the new name with the RTN button.  When editing Flight Mode names this procedure will restore the original name and the edit fails.

**Comment by WismyYao** [comment]
Thanks for your bug report.

**Comment by choochoo2** [comment]
Fixed in 1.3.06
