### ISSUE TITLE
 Incorrect value shown on LSW page - Horus x12s - FROS - Fw:1.6.04 beta lbt 

### ISSUE THREAD

**Issue by Lombardoa** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#257]
I describe a small problem with LSW functions
As shown in ph1, I entered the value of 4.7V on LSW4, to monitor the voltage of the RXbattery.
While on the first page (ph2) it shows me a value of 4.6V.
Thanks for your support.

![ph1](https://user-images.githubusercontent.com/50540767/62598837-d8c29680-b8ea-11e9-8946-5dd3430e6c97.jpg)

![ph2](https://user-images.githubusercontent.com/50540767/62598841-de1fe100-b8ea-11e9-9a09-36d4bde2a519.jpg)

**Comment by Adelaxie** [comment]
its caused by losing of precision during data conversion.

**Comment by Lombardoa** [comment]
Hi Adela,
thanks for your answer...
I remember that i no have this losing of precision with old fw 1.5.05 LBT...
It's possible improve this precision?...
Thank again...

A.Lombardo




Il 09/08/2019 05:47, Adela ha scritto:
