### ISSUE TITLE
X10 Express can't bind receivers in ACCST D16 protocol

### ISSUE THREAD

**Issue by isidresa** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#271]
X10 EXPRESS  with FrOS FW V2.0.02 (Beta)
I Have several X6R and X8R Receivers and I can't bind any of these whit X10 Express in ACCST D16 mode. The FW version of receivers are: 2.1.0 LBT
In may Horus X12S Transmitter all of them are binding without problem.

**Comment by Burgerman-X10express** [comment]
You need to wait till the new 2.10 update is available for your TX for its internal module before that will work.

**Comment by isidresa** [comment]
Yes I know and I wait for a new FW version, what may question is wend this new version will be available.
