### ISSUE TITLE
CURVE LIB

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#42]
CURVE LIB / Multi Line. Field for "FILE NAME" to small. Same in English and German.

In addition, a name is missing before the field where you enter the number of points for a curve.

I do not understand this all. O.k. Field for "FILE NAME" is to smal. But bellow th numbers are normal the NAME of the file. But if I change the Number for excample from 11 to 3. Then I can see in 21-point line that the number off points are changed from 11 to 3. So it is not the name, but the quantity of points I can set.

**Comment by EngelMT** [comment]
If you have a look to DR/EXPO you will find out that it is right here. So it seams to be a mistake in CURVE LIB.

**Comment by Adelaxie** [comment]
#23  closed ,dumplicate post

**Comment by Adelaxie** [comment]
>Field for "FILE NAME" is to smal. But bellow th numbers are normal the NAME of the file.But if I change the Number for excample from 11 to 3. Then I can see in 21-point line that the number off points are changed from 11 to 3. So it is not the name, but the quantity of points I can set.

Donot understand what you mean.

>

**Comment by Adelaxie** [comment]
out of date issue?

**Comment by EngelMT** [comment]
Can be closed. Field is bigger now and works in english and for German I found a shortcut.

Only for your information. 1.4.04 cut letters from WL TRANSMISSION.

**Comment by Adelaxie** [comment]
Thanks and you can close issues set by yourselves actually.
WL Trainer page you mean I guess , will check.
