### ISSUE TITLE
THR-MIX Helicopter 1.2.23L Temp2

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#54]
Can be a bug we had not found in the past or can be a bug with the new Firmware. If you set THR-MIX ACTIV, Set RATES and now you will set a switch the transmitter can be frosen. I have had it two times. But now it works.

**Comment by janekx** [comment]
Self repairing bugs, good :) Horus got AI

**Comment by Adelaxie** [comment]
issues out of date
