### ISSUE TITLE
Sound Alarm too loud, Poti Problem?

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#73]
Customers informed us that it is not possible to make the volume for the voice announcement quiet enough. I have tried it and must say that the customers are right. With earphones it is particularly annoying.

Can that be at the Potis? Because they have a range of about 10-15 degrees where they do not show any effect. This is also a big disadvantage when the potentiators are used for functions such as flaps etc.

**Comment by Adelaxie** [comment]
And now?

**Comment by EngelMT** [comment]
Seems to be better with 1.4.04. Possible to adjust over the complete way of 360 degrees of the poti. So I think you can close this issue.

Sorry, but I did not pursue Git Hub, because nothing happened there.

**Comment by Adelaxie** [comment]
It is OK and i will close it then.thanks
