### ISSUE TITLE
EXTRA MIX

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#76]
I use STCK. Mode 1. Means THR on Stick J2. If I move this stick in EXTRA MIX to set SRC it comes ELE (J3). Seems to be not the right stick mode. But I have set it right. If I check Input and Output and the Servo Monitor I see that Stick J2 it THR.

I check it again with my production unit and 1.2.25. It is the same. I will explane again what I do.

-create a new model in mode Airplane
-Stick Mode 1
-Check the input. It shows THR with J2. It is o.k.
-Open EX Mixer, scroll to SRC and press "Enter Button"
-Move the right stick (J2)
-The setting is ELE and J3

I check it with this production unit and the 1.2.25 and 1.2.25 EU and now with the 1.2.25 NON EU. all is the same.

Now I create an airplane with Stick Mode 2 and do the same. Now it shows ELE but J2!!!!

I am sure that here is a fault!!

**Comment by EngelMT** [comment]
To get the confusion completely the following test.

Now I change my Config Files to the files who are added in the update folder from FrSky. Now the setting in the Input Map is THR and J3!!.

But if I move the Stick J2 now in Extra Mix than the setting in SRC will be also ELE and J2 like as wrote above!!!

O.k. I change the setting in Input Map ELE and J3 and THR and J2. In Extra Mix will be the same problem. Move the right Stick J2 and it will be set ELE J3.

It is not normal, or?!?!?

**Comment by WismyYao** [comment]
Fixed problem
