### ISSUE TITLE
1.2.25L Custom / MIXER Field for switch to smal. In English and German.

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#81]
Field for switch to smal. In English and German.

![custom_mixer](https://cloud.githubusercontent.com/assets/16795828/22029551/2e1afd0a-dcdb-11e6-9fc0-305d72a6190e.jpg)

**Comment by Adelaxie** [comment]
English version fixed. German need special files to check.
