### ISSUE TITLE
Incremental encoder

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/HORUS-X10-X10S-X12S-bug-report#82]
Customers inform us about problems with the Incremental encoder. Means black button for scroll and enter.

Button is broken by several customers. But more important is the problem to find the right position by scrolling before press enter. I think FrSky mus change the resolution per 360 degree turn.

**Comment by Adelaxie** [comment]
We have replaced the plastic button part into new materials.
For the wrong operation ,will try to make it better.

**Comment by EngelMT** [comment]
Alexa, please have a look to the Q X7. Ther the incremental encoder works perfect I think. So it must be possible to make modifications on Horus. Best was will be to do it by software. Then all customers can benefit from it.

**Comment by Adelaxie** [comment]
Issues out of date
